import type { Lead } from '@/types/lead'
import type { Property } from '@/types/property'
import type { RecommendedAction, Transaction, Task } from '@/types/action'

export const mockLeads: Lead[] = [
  {
    id: 'l1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@gmail.com',
    phone: '(415) 555-0192',
    stage: 'hot',
    score: 88,
    budget: 950000,
    preferredAreas: ['Palo Alto', 'Menlo Park', 'Los Altos'],
    preferences: { minBeds: 3, maxBeds: 4, minBaths: 2, propertyTypes: ['Single Family'] },
    lastContactDaysAgo: 5,
    recentBehavior: ['Viewed 123 Maple Ave 3 times in 24h', 'Saved 2 listings', 'Used mortgage calculator'],
    intentSignals: ['high_view_frequency', 'saved_listing', 'mortgage_calc'],
    assignedAgent: 'James Carter',
    source: 'IDX Website',
  },
  {
    id: 'l2',
    name: 'Mike Reyes',
    email: 'mikereyes@outlook.com',
    phone: '(650) 555-0341',
    stage: 'nurturing',
    score: 61,
    budget: 750000,
    preferredAreas: ['Sunnyvale', 'Santa Clara', 'Mountain View'],
    preferences: { minBeds: 2, maxBeds: 3, minBaths: 2, propertyTypes: ['Condo', 'Townhouse'] },
    lastContactDaysAgo: 8,
    recentBehavior: ['Back on site after 6-day absence', 'Viewed 3 condos'],
    intentSignals: ['back_to_site', 'increased_search_frequency'],
    assignedAgent: 'James Carter',
    source: 'Facebook Ads',
  },
  {
    id: 'l3',
    name: 'Annette Black',
    email: 'annette.black@icloud.com',
    phone: '(408) 555-0587',
    stage: 'active',
    score: 74,
    budget: 1200000,
    preferredAreas: ['Los Altos Hills', 'Saratoga', 'Monte Sereno'],
    preferences: { minBeds: 4, maxBeds: 5, minBaths: 3, propertyTypes: ['Single Family', 'Estate'] },
    lastContactDaysAgo: 2,
    recentBehavior: ['Requested home valuation', 'Viewed 5 luxury listings'],
    intentSignals: ['valuation_request', 'luxury_segment'],
    assignedAgent: 'James Carter',
    source: 'Google Ads',
  },
  {
    id: 'l4',
    name: 'David Park',
    email: 'd.park@stanford.edu',
    phone: '(650) 555-0773',
    stage: 'new',
    score: 52,
    budget: 680000,
    preferredAreas: ['East Palo Alto', 'Redwood City'],
    preferences: { minBeds: 2, maxBeds: 3, minBaths: 1, propertyTypes: ['Condo', 'Single Family'] },
    lastContactDaysAgo: 0,
    recentBehavior: ['Just registered', 'Browsed 8 listings'],
    intentSignals: ['new_lead', 'high_browse_count'],
    assignedAgent: 'James Carter',
    source: 'IDX Website',
  },
  {
    id: 'l5',
    name: 'Linda Torres',
    email: 'ltorres@gmail.com',
    phone: '(510) 555-0229',
    stage: 'cold',
    score: 23,
    budget: 500000,
    preferredAreas: ['Fremont', 'Newark'],
    preferences: { minBeds: 2, maxBeds: 2, minBaths: 1, propertyTypes: ['Condo'] },
    lastContactDaysAgo: 21,
    recentBehavior: ['No activity in 3 weeks'],
    intentSignals: ['cooling_down'],
    assignedAgent: 'James Carter',
    source: 'Open House',
  },
  {
    id: 'l6',
    name: 'Robert Nguyen',
    email: 'rnguyen@hotmail.com',
    phone: '(408) 555-0914',
    stage: 'hot',
    score: 82,
    budget: 880000,
    preferredAreas: ['Campbell', 'Los Gatos', 'Saratoga'],
    preferences: { minBeds: 3, maxBeds: 4, minBaths: 2, propertyTypes: ['Single Family'] },
    lastContactDaysAgo: 3,
    recentBehavior: ['Scheduled a showing', 'Viewed 7 listings this week'],
    intentSignals: ['showing_request', 'high_intent'],
    assignedAgent: 'James Carter',
    source: 'Zillow',
  },
]

export const mockProperties: Property[] = [
  {
    id: 'p1',
    address: '123 Maple Ave',
    city: 'Palo Alto',
    state: 'CA',
    zip: '94301',
    price: 925000,
    beds: 3,
    baths: 2,
    sqft: 1640,
    tags: ['updated kitchen', 'large yard', 'quiet street'],
    status: 'active',
    daysOnMarket: 4,
    mlsNumber: 'ML81924501',
  },
  {
    id: 'p2',
    address: '87 Valencia St',
    city: 'Menlo Park',
    state: 'CA',
    zip: '94025',
    price: 1050000,
    beds: 4,
    baths: 3,
    sqft: 2100,
    tags: ['corner lot', 'EV charger', 'top-rated school district'],
    status: 'back_on_market',
    daysOnMarket: 31,
    mlsNumber: 'ML81918874',
  },
  {
    id: 'p3',
    address: '2118 Thornridge Cir',
    city: 'Sunnyvale',
    state: 'CA',
    zip: '94086',
    price: 740000,
    beds: 2,
    baths: 2,
    sqft: 1120,
    tags: ['HOA community', 'pool', 'near tech corridor'],
    status: 'active',
    daysOnMarket: 9,
    mlsNumber: 'ML81929032',
  },
  {
    id: 'p4',
    address: '26096 Dougherty Pl',
    city: 'Los Altos Hills',
    state: 'CA',
    zip: '94022',
    price: 1190000,
    beds: 4,
    baths: 3,
    sqft: 2800,
    tags: ['hilltop views', 'pool', 'detached ADU'],
    status: 'active',
    daysOnMarket: 2,
    mlsNumber: 'ML81931204',
  },
  {
    id: 'p5',
    address: '182 Saint Peter St',
    city: 'Campbell',
    state: 'CA',
    zip: '95008',
    price: 870000,
    beds: 3,
    baths: 2,
    sqft: 1780,
    tags: ['renovated', 'private garden', 'walk to downtown'],
    status: 'back_on_market',
    daysOnMarket: 44,
    mlsNumber: 'ML81905112',
  },
  {
    id: 'p6',
    address: '3931 Via Montalvo',
    city: 'Carmel',
    state: 'CA',
    zip: '93923',
    price: 680000,
    beds: 2,
    baths: 2,
    sqft: 1050,
    tags: ['ocean views', 'remodeled', 'gated'],
    status: 'active',
    daysOnMarket: 6,
    mlsNumber: 'ML81927761',
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: 't1',
    address: '3931 Via Montalvo, Campbell, CA 95008',
    stage: 'inspection',
    closingDate: '2026-05-10',
    nextDeadline: '2026-04-20',
    nextDeadlineLabel: 'Inspection deadline',
    leadId: 'l6',
    agentName: 'James Carter',
    salePrice: 870000,
    daysUntilDeadline: 2,
  },
  {
    id: 't2',
    address: '87 Valencia St, Half Moon Bay, CA 94019',
    stage: 'appraisal',
    closingDate: '2026-04-28',
    nextDeadline: '2026-04-19',
    nextDeadlineLabel: 'Appraisal contingency expires',
    leadId: 'l3',
    agentName: 'James Carter',
    salePrice: 1045000,
    daysUntilDeadline: 1,
  },
  {
    id: 't3',
    address: '2118 Thornridge Cir, Syracuse, CT 35...',
    stage: 'closing',
    closingDate: '2026-04-22',
    nextDeadline: '2026-04-22',
    nextDeadlineLabel: 'Closing date',
    leadId: 'l1',
    agentName: 'James Carter',
    salePrice: 735000,
    daysUntilDeadline: 4,
  },
]

export const mockTasks: Task[] = [
  {
    id: 'task1',
    type: 'call',
    title: 'Call back for more information',
    leadId: 'l2',
    dueTime: '10:00 AM',
    completed: false,
  },
  {
    id: 'task2',
    type: 'call',
    title: 'Call-back follow up',
    leadId: 'l6',
    dueTime: 'Anytime',
    completed: true,
  },
  {
    id: 'task3',
    type: 'email',
    title: 'Spanish speaking only follow up',
    leadId: 'l5',
    dueTime: '12:00 PM',
    completed: false,
  },
  {
    id: 'task4',
    type: 'text',
    title: 'Send listing info',
    leadId: 'l4',
    dueTime: '2:00 PM',
    completed: false,
  },
]

export const agentProfile = {
  name: 'James Carter',
  title: 'Senior Real Estate Agent',
  brokerage: 'Lofty Realty',
  avatar: null,
}
